site_name: "RCJ関西ブロック運営マニュアル"

theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'cyan'
    accent: 'pink'
  feature:
    tabs: true
  #logo: 'images/logo_long.png'
extra:
  search:
    language: 'jp'
markdown_extensions:
  - admonition
  - codehilite

# Page tree
nav:
  - 'Home': 'index.md'